title: Pejskařův průvodce 
baseURL: https://boring-mccarthy-e2e932.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139409377-1
menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors
  addThis: "ra-5cd17a2ddf11b688"

