title: Pejskařův průvodce 
baseURL: https://boring-mccarthy-e2e932.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalitycs: "UA-139409377-2"
menu:
  main:
    - name: Domů
      url: /
      weight: 10
    - name: Články
      identifier: post
      url: /post/
      weight: 20

params:
  description: Vše co potřebuje správný pejskař znát.
  addThis: "ra-5cd17a2ddf11b688"

